Add abstract wallet type and its basic implementation.
VRublevski/wallet pull request #1
Opened 2020-12-21 14:59 UTC by VRublevski

2020-12-22 00:45 UTC, papahmsolo requested changes
Good start Vlad!

A note on tests: it would be good to test the wallet balance is correct after you've done some balance operations.

2020-12-22 00:45 UTC, papahmsolo commented on wallet.go
> +}
Can we withdraw more than `w.balance`?

2020-12-22 00:45 UTC, papahmsolo commented on wallet.go
> +}
Can we deposit a negative amount of bitcoins?

2020-12-22 00:45 UTC, papahmsolo commented on wallet.go
> +}
Are we going to implement this interface more than once? If not, we probably don't need it. do we?

2020-12-22 07:31 UTC, VRublevski commented on wallet.go
> +}
I thought that we would create an implementation that is not thread safe and another one that is.

2020-12-22 09:04 UTC, VRublevski commented on wallet.go
> +}
@papahmsolo I thought at first that this way we could implement a notion of debt . Now I understand that this is an issue. I solved it.

2020-12-22 09:05 UTC, VRublevski commented on wallet.go
> +}
@papahmsolo I've fixed that.

2020-12-22 09:42 UTC, papahmsolo commented on error.go
> +
There's an easier way for this: `errors.New()`

2020-12-22 09:42 UTC, papahmsolo commented on wallet.go
> +}
@VRublevski Ah, no we can do it within the same type. But even if we wanted that, it's always good not to create abstractions before it's actually needed. Read up on "interface pollution"

2020-12-22 09:48 UTC, papahmsolo requested changes
It would be better to keep errors to the place where they actually occur, so no need for `error.go`, they can stay in `wallet.go`

2020-12-22 09:50 UTC, VRublevski commented on error.go
> +
@papahmsolo I wanted that the users be able to determine the type of an error and act upon it respectively. Also I wanted to provide some information with the error. It looks like none of these can be achieved with `errors.New()`

2020-12-22 09:54 UTC, papahmsolo reviewed
Looks great Vlad, we're on a good track!

2020-12-22 09:54 UTC, papahmsolo commented on wallet_test.go
> +	}
Do we really care the wallet is equal or we rather want to test the wallet's property? Such as the balance is correct after deposit and withdrawal?

2020-12-22 09:54 UTC, papahmsolo commented on wallet_test.go
> +	}
Good idea! Worth to make it a test helper function

2020-12-22 09:54 UTC, papahmsolo commented on wallet_test.go
> +		wallet := Wallet{200}
Remember you won't be able to assign the balance directly outside this package, but luckily you have `Deposit()` for that.

2020-12-22 11:52 UTC, VRublevski commented on wallet.go
> +}
@papahmsolo Now I know about this good practice. I got rid of the `Interface`.

2020-12-22 11:52 UTC, VRublevski commented on error.go
> +
@papahmsolo I followed your advice.

2020-12-22 11:53 UTC, VRublevski commented on wallet_test.go
> +	}
@papahmsolo No, we don't. Now I check for the wallet properties in tests.

2020-12-22 11:54 UTC, VRublevski commented on wallet_test.go
> +	}
@papahmsolo I made a helper function.

2020-12-22 11:56 UTC, VRublevski commented on wallet_test.go
> +		wallet := Wallet{200}
@papahmsolo That's true. I use `Desposit()` as part of tests' transactions now.

2020-12-22 13:30 UTC, papahmsolo requested changes
Not bad at all!

You got the idea with `t.Run()` right. But let's think what are the actual scenarios we want to test?

2020-12-22 13:30 UTC, papahmsolo commented on wallet.go
> +}
No need to return the balance, we have a special method for that

2020-12-22 13:30 UTC, papahmsolo commented on wallet.go
> +}
Same with `Withdraw`

2020-12-22 13:30 UTC, papahmsolo commented on wallet_test.go
> +		},
These two tests are doing the same thing? Do we need that many?

2020-12-22 13:30 UTC, papahmsolo commented on wallet_test.go
> +			want:  .0,
Should this test pass?

2020-12-22 13:31 UTC, papahmsolo commented on wallet_test.go
> +}
Nice! Read about `t.Helper()`

2020-12-22 13:32 UTC, papahmsolo commented on wallet.go
> +// of the wallet and an error if an operation was unsuccesful.
unsuccessful

2020-12-22 15:46 UTC, VRublevski commented on wallet.go
> +}
@papahmsolo I removed redundant Bitcoin return value.

2020-12-22 15:48 UTC, VRublevski commented on wallet_test.go
> +			want:  .0,
@papahmsolo I deleted all of these tests. Think they are overkill.

2020-12-22 15:49 UTC, VRublevski commented on wallet_test.go
> +}
@papahmsolo I mark every such function as a helper now.

2020-12-23 10:11 UTC, papahmsolo requested changes
Good job!

`testInsufficientBalance` and `testNegativeAmount` helpers are kind of the same, aren't they? Maybe we can combine them into one?

2020-12-23 10:16 UTC, papahmsolo requested changes
A couple of other thoughts

2020-12-23 10:16 UTC, papahmsolo commented on wallet_test.go
> +	}
What do you mean by correct? Positive?

2020-12-23 10:16 UTC, papahmsolo commented on wallet_test.go
> +	}
This is not a problem at all, but it would be cool to see something like `Balance mismatch: want: 100 BTC, but got: 99 BTC` when the test fails. To have this custom print format for Bitcoin type rather than using the float64.

2020-12-23 10:59 UTC, VRublevski commented on wallet_test.go
> +	}
Yes, I do. I've changed the message to reflect this.

2020-12-23 11:02 UTC, VRublevski commented on wallet_test.go
> +	}
@papahmsolo I've added an implementation of `Stringer` interface for more pleasant output.

2020-12-23 13:46 UTC, papahmsolo requested changes
Perfect!

One last thing, let's also make sure we don't get an error when we don't expect one. This applies to positive test scenarios.

2020-12-23 15:34 UTC, papahmsolo requested changes
- We probably don't need any ifs here along with `errManager` wrapper. A test can be as simple as this:

```
		wallet := &Wallet{}

		err := wallet.Deposit(100)
		assertError(t, nil, err)

		err = wallet.Withdraw(100)
		assertError(t, nil, err)

		assertBalance(t, Bitcoin(0), wallet.Balance())
```

- Also you won't be able to `push -f` on a real project, the branch would be protected. Resolve conflicts instead.

2020-12-23 16:23 UTC, VRublevski commented
@papahmsolo I learned this the hard way. As for the forced push I made a typo in a commit message and pushed it on Github. I wanted to correct it locally and on Github. I didn't realize that it would have any consequences as I thought that nobody except of me had a local copy of the repository's history. It's the second lesson I learned today.

2020-12-24 07:09 UTC, papahmsolo requested changes
Our wallet works with Bitcoins, not floats, even though these types are compatible. So it makes sense to say that explicitly: 
`wallet.Deposit(Bitcoin(10))
assertBalance(t, Bitcoin(10), wallet.Balance())`

2020-12-24 07:58 UTC, papahmsolo approved these changes
Nice! Keep up with the great work!

2020-12-24 07:58 UTC, merged